export const addressSagaActions = {
  UPDATE_CURRENT_ADDRESS: "UPDATE_CURRENT_ADDRESS",
  CREATE_ADDRESS: "CREATE_ADDRESS",
  EDIT_ADDRESS: "EDIT_ADDRESS",
  GET_ADDRESS_LIST: "GET_ADDRESS_LIST",
  DELETE_ADDRESS: "DELETE_ADDRESS",
};
 