export const authSagaActions = {
  CREATE_AWS_ACCOUNT: "CREATE_AWS_ACCOUNT",
  SIGNIN_AWS_ACCOUNT: "SIGNIN_AWS_ACCOUNT",
  CONFIRM_SIGNIN: "CONFIRM_SIGNIN",
  CONFIRM_SIGNUP: "CONFIRM_SIGNUP",
  SET_CONFIRMATION_STATUS: "SET_CONFIRMATION_STATUS",
  SIGNOUT: "SIGNOUT",
};
