export const cartSagaActions = {
  ADD_TO_CART: "ADD_TO_CART", //done
  REMOVE_FROM_CART: "REMOVE_FROM_CART", //done
  UPDATE_CART: "UPDATE_CART",
  APPLY_REWARD_POINT: "APPLY_REWARD_POINT",
  APPLY_COUPONS: "APPLY_COUPONS",
  REMOVE_COUPON: "REMOVE_COUPON",
  EMPTY_CART: "EMPTY_CART", //done
  CREATE_CART: "CREATE_CART",
  VALIDATE_CART: "VALIDATE_CART",
  UPDATE_CART_ID: "UPDATE_CART_ID",
  UPDATE_CART_ID_LOADING: "UPDATE_CART_ID_LOADING",
  STORE_COUPON: "STORE_COUPON",
};
