export const cartSagaActions = {
  ADD_TO_CART: "ADD_TO_CART", //done
  REMOVE_FROM_CART: "REMOVE_FROM_CART", //done
  UPDATE_CART: "UPDATE_CART", //done
  APPLY_REWARD_POINT: "APPLY_REWARD_POINT",
  APPLY_COUPONS: "APPLY_COUPONS",
  REMOVE_COUPON: "REMOVE_COUPON",
  EMPTY_CART: "EMPTY_CART", //done
  CREATE_CART: "CREATE_CART",
  VALIDATE_CART: "VALIDATE_CART",
  STORED_COUPON_CODE: "STORED_COUPON_CODE",
  CLEAR_STORED_COUPON_CODE: "CLEAR_STORED_COUPON_CODE",
  FETCH_AND_ADD_PRODUCTS_FROM_ENCODED_CART:
    "FETCH_AND_ADD_PRODUCTS_FROM_ENCODED_CART",
  UPDATE_CART_ID: "UPDATE_CART_ID",
  UPDATE_CART_ID_LOADING: "UPDATE_CART_ID_LOADING",
  UPDATE_CART_WITH_SHOPPING_CART_ID: "UPDATE_CART_WITH_SHOPPING_CART_ID",
  MANAGE_CART: "MANAGE_CART",
  UPDATE_CART_COUPON: "UPDATE_CART_COUPON",
  VALIDATE_CART_ON_ERROR: "VALIDATE_CART_ON_ERROR",
};
